-- Crear tabla bitacora_reactivaciones
CREATE TABLE IF NOT EXISTS bitacora_reactivaciones (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_reunion INT NOT NULL,
    id_usuario INT NOT NULL,
    justificacion VARCHAR(255) NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (id_reunion) REFERENCES reunion(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (id_usuario) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);
