version: '3.7'

services:
  reutrack:
    build: .
    env_file:
      - .env
    ports:
      - "3100:3100"
    restart: always
    networks:
      reutrack_network:
        ipv4_address: 10.168.241.175

networks:
  reutrack_network:
    driver: bridge
    ipam:
      config:
        - subnet: "10.168.241.0/24"
