openapi: 3.0.0
info:
  title: API de Proyecto
  version: 1.0.0
tags:
  - Proyecto

paths:
  /proyecto:
    get:
      summary: Recuperar todos los proyectos
      tags:
        - Proyecto
      responses:
        '200':
          description: Una lista de proyectos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../schemas/proyecto.json'
    post:
      summary: Crear un nuevo proyecto
      tags:
        - Proyecto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/proyecto.json'
      responses:
        '201':
          description: Proyecto creado
          content:
            application/json:
              schema:
                $ref: '../schemas/proyecto.json'

  /proyecto/{id}:
    get:
      summary: Recuperar un proyecto específico por ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID del proyecto a recuperar
          schema:
            type: integer
      responses:
        '200':
          description: Objeto de proyecto
          content:
            application/json:
              schema:
                $ref: '../schemas/proyecto.json'
    patch:
      summary: Actualizar un proyecto existente por ID
      tags:
        - Proyecto
      parameters:
        - name: id
          in: path
          required: true
          description: ID del proyecto a actualizar
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/proyecto.json'
      responses:
        '200':
          description: Proyecto actualizado
          content:
            application/json:
              schema:
                $ref: '../schemas/proyecto.json'

  /proyecto/cancelar/{id}:
    patch:
      summary: Cancelar un proyecto por ID
      tags:
        - Proyecto
      parameters:
        - name: id
          in: path
          required: true
          description: ID del proyecto a cancelar
          schema:
            type: integer
      responses:
        '204':
          description: Proyecto cancelado

  /proyecto/finalizar/{id}:
    patch:
      summary: Finalizar un proyecto por ID
      tags:
        - Proyecto
      parameters:
        - name: id
          in: path
          required: true
          description: ID del proyecto a finalizar
          schema:
            type: integer
      responses:
        '204':
          description: Proyecto finalizado

tags:
  - Proyecto
